# slurmigo — act: ACT stage (job submission)
# Params file parsing, wrapper script generation, and job submission.

from __future__ import annotations

import csv
import io
import logging
import os
import re
import stat
import subprocess

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Params file parsing
# ---------------------------------------------------------------------------


def parse_params_file(path: str) -> tuple[list[dict[str, str]], str]:
    """Parse a parameter file and return (list_of_param_dicts, format_type).

    Auto-detects format:
      - Lines with ``=`` → key=value format
      - Lines with ``,`` but no ``=`` → CSV (first line is header)
      - Otherwise → raw text, key="SLURMIGO_LINE"
    """
    with open(path, "r") as f:
        raw_lines = f.readlines()

    # Strip and filter empty / comment lines
    lines = []
    for line in raw_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lines.append(stripped)

    if not lines:
        return [], "keyvalue"

    # Auto-detect format from first data line
    first = lines[0]
    if "=" in first:
        format_type = "keyvalue"
    elif "," in first and "=" not in first:
        format_type = "csv"
    else:
        format_type = "raw"

    params: list[dict[str, str]] = []

    if format_type == "keyvalue":
        for line in lines:
            try:
                tokens = line.split()
                entry: dict[str, str] = {}
                for token in tokens:
                    key, value = token.split("=", 1)
                    entry[key] = value
                params.append(entry)
            except ValueError:
                logger.warning("Skipping unparseable key=value line: %s", line)

    elif format_type == "csv":
        header = lines[0]
        data_lines = lines[1:]
        reader = csv.DictReader(
            io.StringIO("\n".join([header] + data_lines)),
        )
        for row in reader:
            try:
                params.append(dict(row))
            except Exception:
                logger.warning("Skipping unparseable CSV row: %s", row)

    else:
        # Raw text — each line becomes SLURMIGO_LINE
        for line in lines:
            params.append({"SLURMIGO_LINE": line})
        format_type = "raw"

    return params, format_type


def count_tasks(path: str) -> int:
    """Count valid (non-empty, non-comment) lines in a params file.

    For CSV files: subtracts 1 for the header row.
    """
    with open(path, "r") as f:
        raw_lines = f.readlines()

    lines = []
    for line in raw_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lines.append(stripped)

    if not lines:
        return 0

    # Detect format to know if first line is a header
    first = lines[0]
    if "," in first and "=" not in first:
        # CSV — header doesn't count
        return len(lines) - 1

    return len(lines)


# ---------------------------------------------------------------------------
# Wrapper generation
# ---------------------------------------------------------------------------


def generate_wrapper(
    task_id: int,
    params: dict[str, str],
    user_script: str,
    state_dir: str,
) -> str:
    """Generate a bash wrapper that exports params and sources the user script.

    Creates ``{state_dir}/wrappers/task_{task_id}.sh``, makes it executable,
    and returns its absolute path.
    """
    wrappers_dir = os.path.join(state_dir, "wrappers")
    os.makedirs(wrappers_dir, exist_ok=True)

    wrapper_path = os.path.join(wrappers_dir, f"task_{task_id}.sh")
    abs_user_script = os.path.abspath(user_script)

    lines = [
        "#!/bin/bash",
        "# Generated by slurmigo — do not edit",
        f"# Task ID: {task_id}",
    ]

    for key, value in params.items():
        lines.append(f'export {key}="{value}"')

    lines.append(f"export SLURMIGO_TASK_ID={task_id}")
    lines.append(f'source "{abs_user_script}"')
    lines.append("")  # trailing newline

    with open(wrapper_path, "w") as f:
        f.write("\n".join(lines))

    os.chmod(
        wrapper_path,
        stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH,
    )  # 755

    return os.path.abspath(wrapper_path)


def build_sbatch_args(
    directives: dict[str, str],
    overrides: dict[str, str] | None = None,
) -> list[str]:
    """Convert a directive dict to a list of sbatch CLI args.

    Each key-value becomes ``--key=value``.  If *overrides* is provided,
    those key-value pairs replace the originals.
    """
    merged = dict(directives)
    if overrides:
        merged.update(overrides)

    args: list[str] = []
    for key, value in merged.items():
        if value == "":
            # Boolean flag like --requeue (no value)
            args.append(f"--{key}")
        else:
            args.append(f"--{key}={value}")

    return args


# ---------------------------------------------------------------------------
# Submission
# ---------------------------------------------------------------------------


def submit_job(wrapper_path: str, sbatch_args: list[str]) -> str | None:
    """Submit a job via sbatch and return the job ID string, or None on failure."""
    cmd_list = ["sbatch"] + sbatch_args + [wrapper_path]

    try:
        result = subprocess.run(
            cmd_list,
            capture_output=True,
            text=True,
            check=True,
        )
        match = re.search(r"Submitted batch job (\d+)", result.stdout)
        if match:
            return match.group(1)
        logger.error("sbatch output did not contain job ID: %s", result.stdout)
        return None
    except subprocess.CalledProcessError as exc:
        logger.error("sbatch failed (rc=%d): %s", exc.returncode, exc.stderr)
        return None
    except FileNotFoundError:
        logger.error("sbatch command not found")
        return None


# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------


def cleanup_wrappers(state_dir: str, keep_last: int = 0) -> None:
    """Remove wrapper scripts from ``{state_dir}/wrappers/``.

    If *keep_last* > 0, keep the most recently modified *keep_last* files
    and delete the rest.  If *keep_last* == 0, delete all.
    """
    wrappers_dir = os.path.join(state_dir, "wrappers")
    if not os.path.isdir(wrappers_dir):
        return

    files = [
        os.path.join(wrappers_dir, f)
        for f in os.listdir(wrappers_dir)
        if os.path.isfile(os.path.join(wrappers_dir, f))
    ]

    if keep_last <= 0:
        for fp in files:
            os.remove(fp)
        return

    # Sort by modification time, newest first
    files.sort(key=lambda p: os.path.getmtime(p), reverse=True)

    for fp in files[keep_last:]:
        os.remove(fp)
